### PR TITLE
support TinyGo SDK

### PR DESCRIPTION
**Pull request by mathetake**
Hi folks, I am the author of [TinyGo SDK](https://github.com/tetratelabs/proxy-wasm-go-sdk) and I am thinking of adding the support of TinyGo SDK in wasme since It's now compatible istio/envoy with 1.7.x as of its 0.0.3 release. 

~This is still in WIP but I need the direction from the maintainers here to add the build command support for TinyGo SDK.~

Thanks!
___

resolves https://github.com/solo-io/wasm/issues/31 ?

### CODE REVIEW

**Comment by yuval-k** [comment]
look good! are you able to add an e2e similar to this one?

https://github.com/solo-io/wasm/blob/cc1968997db6e1efd3f0bc6a6cc67ac1a5dac540/tools/wasme/cli/test/e2e/build/build_test.go#L130

This will help us to catch regressions when istio 1.8 will be out.

**Comment by yuval-k** [comment]
as for the build command, the details are as follows:

- update the build container to have your build tools: `tools/wasme/cli/builder/Dockerfile`
-  add a build subcommand: `tools/wasme/cli/pkg/cmd/build/go.go` that runs your build see `runBuild` function

(see an example with rust here: https://github.com/solo-io/wasm/commit/911d0085bce78838de883f5aa54332de79458302)

**Comment by mathetake** [comment]
@yuval-k Thank you for comments, and now I think it's ready for review! PTAL :smile:

**Review by yuval-k — APPROVED** [review]

**Comment by yuval-k** [comment]
thank you!

**Pull request merged**
