### PR TITLE
More rust example improvements

### PR DESCRIPTION
**Pull request by corporealshift**
I've made some improvements to the example documentation, as well as provided an example of adding/replacing headers in an http response. I also generated more of the bindings from the cpp envoy wasm abi using bindgen. I think this may also have corrected some inaccuracies with types in function signatures but i haven't tested all the functions.

### CODE REVIEW

**Comment by ilackarms** [comment]
this is an awesome contribution! I'd like a review from @EItanya or @yuval-k in order to move forward

**Comment by yuval-k** [comment]
sorry about the delay; since we re-org the structure, i've cherry picked squashed this PR to fit the new structure; it is now in master, so I'm closing this.
Thank you!

**Pull request closed without merging**
